version: "3"
services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      - REDIS_URL=redis:6379
  backend2:
    build: ./backend
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      - REDIS_URL=redis:6379
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run dev
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
volumes:
  mongodb_data:
  redis_data:
